import mongoose, { ObjectId } from 'mongoose';
import {
	string,
	number,
	object,
	array,
	SchemaOf,
	InferType,
} from 'yup';
import { TypedSchema } from 'yup/lib/util/types';

// funky casting to avoid undefined
type Nested<T extends TypedSchema> = SchemaOf<InferType<T>>

const DiscordUser = object({
	discordHandle: string().required(),
	discordId: string().required(),
});

export const Reward = object({
	currency: string().min(0).required(),
	amount: number().min(0).required(),
	scale: number().min(0).required(),
	amountWithoutScale: number().min(0).required(),
}) 

const StatusHistory = object({
	status: string(),
	setAt: string(),
});

/* Global typing for Bounties */
export const BountySchema = object({
	title: string().required(),
	description: string().required(),
	criteria: string().required(),
	customer_id: string().required(),
	status: string().required(),
	reward: Reward.required() as Nested<typeof Reward>,
	
	statusHistory: array(
		StatusHistory as Nested<typeof StatusHistory>
	).optional(),
		
	discordMessageId: string().optional(),
	submissionNotes: string().optional(),
	submissionUrl: string().optional(),
	season: number().optional(),
	dueAt: string().optional(),

	createdAt: string().optional(),
	claimedAt: string().optional(),
	submittedAt: string().optional(),
	reviewedAt: string().optional(),
	
	createdBy: DiscordUser.required() as Nested<typeof DiscordUser>,
	claimedBy: DiscordUser.optional() as Nested<typeof DiscordUser>,
	submittedBy: DiscordUser.required() as Nested<typeof DiscordUser>,
	reviewedBy: DiscordUser.optional() as Nested<typeof DiscordUser>,
});




// Generated by https://quicktype.io

export interface Bounty {
	success: boolean;
	data:    Datum[];
}

export interface Datum {
	statusHistory:     StatusHistory[];
	_id:               string;
	season:            number;
	title:             string;
	description:       string;
	criteria:          string;
	reward:            Reward;
	createdBy:         EdBy;
	createdAt:         string;
	status:            Status;
	dueAt:             string;
	discordMessageId?: string;
	claimedAt?:        string;
	claimedBy?:        EdBy;
	submissionNotes?:  null;
	submissionUrl?:    null | string;
	submittedAt?:      string;
	submittedBy?:      EdBy;
	reviewedAt?:       string;
	reviewedBy?:       EdBy;
	customer_id:       string;
	editKey?:          string;
}

export interface EdBy {
	discordHandle: string;
	discordId:     string;
	iconUrl?:      null | string;
}

export interface Reward {
	currency: Currency;
	amount:   number;
	scale:    number;
}

export enum Currency {
	Bank = "bank",
	CurrencyBANK = "BANK",
	CurrencyBank = "Bank",
}

export enum Status {
	Completed = "Completed",
	Draft = "Draft",
	InProgress = "In-Progress",
	InReview = "In-Review",
	Open = "Open",
}

export interface StatusHistory {
	status: Status;
	setAt:  string;
}

export interface BountyCollection extends InferType<typeof BountySchema> {
	_id: ObjectId;
}

/* BountyBoardSchema will correspond to a collection in your MongoDB database. */
const BountyBoardSchema = new mongoose.Schema({
	title: {
		/* The name of this Bounty */

		type: String,
	},
	customer_id: {
		/* the DAO under which this bounty belongs */

		type: String,
	},
	season: {
		/* The season of this Bounty */

		type: Number,
	},
	description: {
		/* A short description of the Bounty */

		type: String,
	},
	criteria: {
		/* Acceptance criteria of deliverables for the Bounty to be marked complete. */

		type: String,
	},
	reward: {
		/* Bounty reward */

		currency: String,
		amount: Number,
		scale: Number,
		amountWithoutScale: Number,
		type: Object,
	},
	createdBy: {
		/* Discord identity of bounty creator */

		discordHandle: String,
		discordId: Number,
		type: Object,
	},
	createdAt: {
		/* Date of Bounty creation */

		type: String,
	},
	dueAt: {
		/* Bounty Expiration */

		type: String,
	},
	discordMessageId: {
		type: String,
	},
	status: {
		/* Bounty Status */
		/* "Draft", "Open", "In-Progress", "In-Review", "Completed", "Deleted" */
		type: String,
	},
	statusHistory: {
		type: Array,
	},
	claimedBy: {
		discordHandle: String,
		discordId: Number,
		type: Object,
	},
	claimedAt: {
		type: String,
	},
	submissionNotes: {
		type: String,
	},
	submissionUrl: {
		type: String,
	},
	submittedAt: {
		type: String,
	},
	submittedBy: {
		discordHandle: String,
		discordId: Number,
		type: Object,
	},
	reviewedAt: {
		type: String,
	},
	reviewedBy: {
		discordHandle: String,
		discordId: Number,
		type: Object,
	},
});

export default mongoose.models.Bounty as mongoose.Model<BountyCollection> ||
  mongoose.model<BountyCollection>('Bounty', BountyBoardSchema);
