# TOML configuration https://toml.io/en/
[build]
  command = "env-cmd -f .env.qa next build packages/react-app"
  publish = "packages/react-app/dist"

[dev]
  command = "yarn dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"