version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .:/usr/tmp/mongo

  mongo-seed:
    build:
      context: '.'
    links:
      - mongo
    depends_on:
      - mongo
