name: Deploy to QA Environment
on:
    push:
        branches:
          - 'develop'
    pull_request:
        branches:
          - 'develop'
          - 'release/**'
          - 'main'
jobs:
  deploy:
    environment:
      name: preview
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install Dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build Output Directory
        run: yarn build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './packages/react-app/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_AUTH_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          netlify-config-path: './packages/react-app/netlify.toml'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
